#!/bin/bash
${KBHOME}/bin/createdb -p ${KBPORT}
${KBHOME}/bin/psql -p ${KBPORT} -c "create role ${REPLICATIONUSER} login replication encrypted password '123456';"
${KBHOME}/bin/psql -p ${KBPORT} -c "select sys_create_physical_replication_slot('${SLOTNAME}');"
