#!/bin/bash

extra=$1
all=("KBDATA" "KBUSER")
for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
        if [ -z ${systemVar} ];then
                echo "please run initbashrc first"
                exit 1
        fi
	systemVar=
done

if [ ! -d $KBHOME ]; then
        echo "no HOME exist"
        exit 1
fi

${KBHOME}/bin/initdb -D $KBDATA -E UTF8 --locale=C -U $KBUSER -W -m oracle ${extra}

# set log open
CONF=${KBDATA}/postgresql.conf
echo "logging_collector = on">>${CONF}
echo "log_directory = 'log'" >>${CONF}


#添加master参数
echo "listen_addresses='*'" >> ${CONF}
echo "wal_level=replica" >>${CONF}
echo "max_wal_senders=2" >>${CONF}
#echo "wal_keep_segments=64" >>${CONF}
echo "max_connections=500" >>${CONF}
#add prepared
echo "max_prepared_transactions=10" >>${CONF}
#添加hba参数
HBA=${KBDATA}/pg_hba.conf
echo "host    replication    ${REPLICATIONUSER}    127.0.0.1/32    trust" >>${HBA}
