#!/bin/bash

extra = $1
all=("KBDATA" "KBUSER")
for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
        if [ -z ${systemVar} ];then
                echo "please run initbashrc first"
                exit 1
        fi
	systemVar=
done

initdb -D $KBDATA -E UTF8 --locale=C -U $KBUSER -W -m oracle ${extra}
