#!/bin/bash
extra=${1}
#check bashrc

all=("KBCODE" "KBSLAVEHOME" "KBLOG")

mustExist=( "KBCODE" )

mayExist=("KBSLAVEHOME" "KBLOG")

for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
	if [ -z ${systemVar} ];then
		echo "please run initbashrc first"
		exit 1
	fi
	systemVar=
done

for must in ${mustExist[@]}
do
	systemVar=`eval echo '$'"$must"`
	if [ ! -d ${systemVar} ]; then
		echo "no ${must} exist"
		exit 1
	fi
	systemVar=
done

for may in ${mayExist[@]}
do
	systemVar=`eval echo '$'"$may"`
	if [ ! -d ${systemVar} ];then
		echo "mkdir -p ${systemVar}"
		mkdir -p ${systemVar}
	fi
	systemVar=
done

set -e
#configure
echo "#################################################configure#######################################"

cd ${KBCODE}
./configure --prefix=${KBSLAVEHOME} --with-zlib --enable-nls --enable-integer-datetimes --with-openssl --enable-cassert --with-libxml --with-uuid=e2fs --enable-debug CFLAGS='-O0 -DKingbaseES' --with-icu ${extra} |tee ${KBLOG}/configure.out

#make
echo "#################################################make ##########################################"
make world |tee ${KBLOG}/compile.log

#install
echo "####################################################install#######################################"
rm -rf ${KBSLAVEHOME}/*
make install-world
