#!/bin/bash
extra=${1}
#check bashrc

all=("PGCODE" "PGHOME" "PGLOG")

mustExist=( "PGCODE" )

mayExist=("PGHOME" "PGLOG")

for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
	if [  -z ${systemVar} ];then
		echo "please run initbashrc first"
		exit 1
	fi
	systemVar=
done

for must in ${mustExist[@]}
do
	systemVar=`eval echo '$'"$must"`
	if [  ! -d ${systemVar} ]; then
		echo "no ${must} exist"
		exit 1
	fi
	systemVar=
done

for may in ${mayExist[@]}
do
	systemVar=`eval echo '$'"$may"`
	if [ ! -d ${systemVar} ];then
		echo "mkdir ${systemVar}"
		mkdir -p ${systemVar}
	fi
	systemVar=
done

set -e
#configure
echo "#################################################configure#######################################"

cd ${PGCODE}
./configure --prefix=${PGHOME} --with-zlib --enable-nls --enable-integer-datetimes --with-openssl --enable-cassert --with-libxml --with-uuid=e2fs --enable-debug CFLAGS='-O0 -g' --with-icu ${extra} |tee ${PGLOG}/configure.out

#make
echo "#################################################make ##########################################"
make world |tee ${PGLOG}/compile.log

#install
echo "####################################################install#######################################"
rm -rf ${PGHOME}/*
make install-world
