#!/bin/bash
extra=${1}
#check bashrc

all=("PGCODE" "PGHOME" "PGLOG")

mustExist=( "PGCODE" )

mayExist=("PGHOME" "PGLOG")

for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
	if [ -z ${systemVar} ];then
		echo "please run initbashrc first"
		exit 1
	fi
	systemVar=
done

for must in ${mustExit[@]}
do
	systemVar=`eval echo '$'"$must"`
	if [ ! -d ${systemVar} ]; then
		echo "no ${must} exist"
		exit 1
	fi
	systemVar=
done

for may in ${mayExisti[@]}
do
	systemVar=`eval echo '$'"$may"`
	if [! -d ${systemVar} ];then
		mkdir -p ${systemVar}
	fi
	systemVar=
done

#configure
echo "#################################################configure#######################################"

cd ${KBCODE}
./configure --prefix=${KBHOME} --with-zlib --enable-nls --enable-integer-datetimes --with-openssl --enable-cassert --with-libxml --with-uuid=e2fs --enable-debug CFLAGS='-O0 -DKingbaseES' --with-icu ${extra} |tee ${KBLOG}/configure.out

#make
echo "#################################################make ##########################################"
make world |tee ${KBLOG}/compile.log

#install
echo "####################################################install#######################################"
rm -rf ${KBHOME}/*
make install-world
