#!/bin/bash
extra=${1}
#check bashrc

all=("PGCODE" "PGSLAVEHOME" "PGLOG")

mustExist=( "PGCODE" )

mayExist=("PGSLAVEHOME" "PGLOG")

for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
	if [ -z ${systemVar} ];then
		echo "please run initbashrc first"
		exit 1
	fi
	systemVar=
done

for must in ${mustExist[@]}
do
	systemVar=`eval echo '$'"$must"`
	if [ ! -d ${systemVar} ]; then
		echo "no ${must} exist"
		exit 1
	fi
	systemVar=
done

for may in ${mayExist[@]}
do
	systemVar=`eval echo '$'"$may"`
	if [ ! -d ${systemVar} ];then
		echo "mkdir -p ${systemVar}"
		mkdir -p ${systemVar}
	fi
	systemVar=
done

set -e
#configure
echo "#################################################configure#######################################"

cd ${PGCODE}
if [ "$(uname)" == "Darwin" ]; then
	CFLAGS='-arch x86_64' LDFLAGS='-arch x86_64'  ./configure --prefix=${PGSLAVEHOME}  --enable-debug --with-libs=/usr/local/lib --with-includes=/usr/local/include |tee ${PGLOG}/configure.out
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
	./configure --prefix=${PGSLAVEHOME} --with-zlib --enable-nls --enable-integer-datetimes --enable-cassert --with-libxml --with-uuid=e2fs --enable-debug CFLAGS='-O0 -g' ${extra} |tee ${PGLOG}/configure.out
fi

#make
echo "#################################################make ##########################################"
make world |tee ${PGLOG}/compile.log

#install
echo "####################################################install#######################################"
rm -rf ${PGSLAVEHOME}/*
make install-world
