#!/bin/bash
all=("PGDATA" "PGHOME")
for key in ${all[@]}
do
	systemVar=`eval echo '$'"$key"`
        if [ -z ${key} ];then
                echo "please run initbashrc first"
                exit 1
        fi
	systemVar=
done
if [ ! -d $PGHOME ]; then
	echo "no HOME exist"
	exit 1	
fi
${PGHOME}/bin/pg_ctl -D $PGDATA -l $PGHOME/logfile start
